// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include "gui_lobby.h"


gui_lobby::gui_lobby(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: gui_lobby::gui_lobby
    notebook_lobby_main = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    panel_lobby_1 = new wxPanel(notebook_lobby_main, -1, wxDefaultPosition, wxDefaultSize, wxNO_BORDER);
    menubar_lobby = new wxMenuBar();
    SetMenuBar(menubar_lobby);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(1001, wxT("Connect"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_1->AppendSeparator();
    wxglade_tmp_menu_1->Append(1002, wxT("Exit"), wxT(""), wxITEM_NORMAL);
    menubar_lobby->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    wxglade_tmp_menu_2->Append(1003, wxT("Configure Spring"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_2->Append(1004, wxT("Configure Omni"), wxT(""), wxITEM_NORMAL);
    menubar_lobby->Append(wxglade_tmp_menu_2, wxT("Options"));
    wxMenu* wxglade_tmp_menu_3 = new wxMenu();
    wxglade_tmp_menu_3->Append(1006, wxT("Join Chatroom"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_3->AppendSeparator();
    wxglade_tmp_menu_3->Append(1007, wxT("Create Battle"), wxT(""), wxITEM_NORMAL);
    menubar_lobby->Append(wxglade_tmp_menu_3, wxT("Game"));
    wxMenu* wxglade_tmp_menu_4 = new wxMenu();
    wxglade_tmp_menu_4->Append(1008, wxT("Credits"), wxT(""), wxITEM_NORMAL);
    menubar_lobby->Append(wxglade_tmp_menu_4, wxT("About"));
    toolbar_lobby = new wxToolBar(this, -1, wxDefaultPosition, wxDefaultSize, wxTB_HORIZONTAL|wxTB_HORZ_LAYOUT);
    SetToolBar(toolbar_lobby);
    toolbar_lobby->SetToolBitmapSize(wxSize(16, 16));
    toolbar_lobby->AddTool(2001, wxT("Connect"), wxBitmap(wxT("resource/toolbar/connect.png"), wxBITMAP_TYPE_ANY), wxNullBitmap, wxITEM_NORMAL, wxT("Connect"), wxT(""));
    toolbar_lobby->AddTool(2002, wxT("Disconnect"), wxBitmap(wxT("resource/toolbar/disconnect.png"), wxBITMAP_TYPE_ANY), wxNullBitmap, wxITEM_NORMAL, wxT("Disconnect"), wxT(""));
    toolbar_lobby->AddSeparator();
    toolbar_lobby->AddTool(2003, wxT("Host Battle"), wxBitmap(wxT("resource/toolbar/host_battle.png"), wxBITMAP_TYPE_ANY), wxNullBitmap, wxITEM_NORMAL, wxT("Host a Battle"), wxT(""));
    toolbar_lobby->AddTool(2004, wxT("Configure Spring"), wxBitmap(wxT("resource/toolbar/spring.png"), wxBITMAP_TYPE_ANY), wxNullBitmap, wxITEM_NORMAL, wxT("Configure Spring"), wxT(""));
    toolbar_lobby->AddTool(2005, wxT("Configure Omni"), wxBitmap(wxT("resource/toolbar/sync.png"), wxBITMAP_TYPE_ANY), wxNullBitmap, wxITEM_NORMAL, wxT("Configure Omni"), wxT(""));
    toolbar_lobby->Realize();
    list_lobby_1_games = new wxListCtrl(this, 901, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER);
    text_lobby_1_chatArea = new wxTextCtrl(panel_lobby_1, 201, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxTE_AUTO_URL|wxTE_LINEWRAP);
    const wxString listbox_lobby_1_people_choices[] = {
        
    };
    listbox_lobby_1_people = new wxListBox(panel_lobby_1, 801, wxDefaultPosition, wxDefaultSize, 0, listbox_lobby_1_people_choices, 0);
    text_lobby_1_chatBox = new wxTextCtrl(panel_lobby_1, 202, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    button_lobby_1_send = new wxButton(panel_lobby_1, 101, wxT("Send"));
    button_lobby_1_clear = new wxButton(panel_lobby_1, 102, wxT("Clear"));

    set_properties();
    do_layout();
    // end wxGlade
}


void gui_lobby::set_properties()
{
    // begin wxGlade: gui_lobby::set_properties
    SetTitle(wxT("Omni - Not Connected"));
    wxIcon _icon;
    _icon.CopyFromBitmap(wxBitmap(wxT("resource/spring-redlogo.png"), wxBITMAP_TYPE_ANY));
    SetIcon(_icon);
    SetSize(wxSize(804, 561));
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_BACKGROUND));
    list_lobby_1_games->SetMinSize(wxSize(801, 150));
    list_lobby_1_games->SetFont(wxFont(9, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("Sans")));
    listbox_lobby_1_people->SetMinSize(wxSize(200, 200));
    button_lobby_1_send->Enable(false);
    button_lobby_1_send->SetDefault();
    // end wxGlade
}


void gui_lobby::do_layout()
{
    // begin wxGlade: gui_lobby::do_layout
    wxFlexGridSizer* grid_lobby_main = new wxFlexGridSizer(3, 3, 0, 0);
    wxFlexGridSizer* grid_lobby_1 = new wxFlexGridSizer(2, 3, 0, 0);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_lobby_1_right = new wxFlexGridSizer(3, 1, 0, 0);
    grid_lobby_main->Add(1, 100, 0, wxADJUST_MINSIZE, 0);
    grid_lobby_main->Add(list_lobby_1_games, 1, wxEXPAND, 0);
    grid_lobby_main->Add(1, 100, 0, wxADJUST_MINSIZE, 0);
    grid_lobby_main->Add(1, 150, 0, wxFIXED_MINSIZE, 0);
    grid_lobby_1->Add(text_lobby_1_chatArea, 0, wxEXPAND, 0);
    grid_lobby_1->Add(5, 150, 0, 0, 0);
    grid_lobby_1_right->Add(listbox_lobby_1_people, 0, wxEXPAND, 0);
    grid_lobby_1_right->AddGrowableRow(0);
    grid_lobby_1_right->AddGrowableRow(2);
    grid_lobby_1_right->AddGrowableCol(0);
    grid_lobby_1->Add(grid_lobby_1_right, 1, wxEXPAND, 0);
    grid_lobby_1->Add(text_lobby_1_chatBox, 0, wxEXPAND, 0);
    grid_lobby_1->Add(5, 20, 0, 0, 0);
    sizer_2->Add(button_lobby_1_send, 0, wxEXPAND, 0);
    sizer_2->Add(button_lobby_1_clear, 0, wxEXPAND, 0);
    grid_lobby_1->Add(sizer_2, 1, wxALIGN_CENTER_HORIZONTAL, 0);
    panel_lobby_1->SetAutoLayout(true);
    panel_lobby_1->SetSizer(grid_lobby_1);
    grid_lobby_1->Fit(panel_lobby_1);
    grid_lobby_1->SetSizeHints(panel_lobby_1);
    grid_lobby_1->AddGrowableRow(0);
    grid_lobby_1->AddGrowableCol(0);
    notebook_lobby_main->AddPage(panel_lobby_1, wxT("LAN"));
    grid_lobby_main->Add(notebook_lobby_main, 1, wxEXPAND, 0);
    grid_lobby_main->Add(2, 150, 0, 0, 0);
    grid_lobby_main->Add(1, 5, 0, 0, 0);
    grid_lobby_main->Add(150, 5, 0, 0, 0);
    grid_lobby_main->Add(1, 5, 0, 0, 0);
    SetAutoLayout(true);
    SetSizer(grid_lobby_main);
    grid_lobby_main->AddGrowableRow(1);
    grid_lobby_main->AddGrowableCol(1);
    Layout();
    Centre();
    // end wxGlade
}

