// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_CHANNEL_H
#define GUI_CHANNEL_H

// begin wxGlade: ::dependencies
// end wxGlade


class gui_channel: public wxFrame {
public:
    // begin wxGlade: gui_channel::ids
    // end wxGlade

    gui_channel(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: gui_channel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_channel::attributes
    wxListBox* list_channel_channels;
    wxTextCtrl* text_channel_channel;
    wxButton* button_channel_join;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_CHANNEL_H
