/*
 * CErrorWindow.java
 *
 * Created on 03 February 2008, 22:55
 */
package org.darkstars.battlehub.framework;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.SwingUtilities;

/**
 *
 * @author  tarendai-std
 */
public class CErrorWindow extends javax.swing.JFrame implements ClipboardOwner {

    Throwable e;
    String msg;
    public static String username = null;

    /** Creates new form CErrorWindow
     * @param e 
     */
    public CErrorWindow(Throwable e) {
        this.e = e;
        msg = e.toString() + "\n";
        msg += e.getLocalizedMessage() + "\n";
        for (StackTraceElement se : e.getStackTrace()) {
            msg += "\t" + se.toString() + "\n";
        }
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                initComponents();
                setVisible(true);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        errorTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        noticeLabel = new javax.swing.JLabel();
        copyButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UnCaught Exception");
        setLocationByPlatform(true);

        errorTextPane.setEditable(false);
        errorTextPane.setText(msg);
        jScrollPane1.setViewportView(errorTextPane);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+10f));
        jLabel1.setText("Uncaught Exception");

        noticeLabel.setText("<html>Please report this to darkstars.co.uk for fixing.");

        copyButton.setText("Copy to Clipboard");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+1));
        jLabel2.setText("Please make sure you have the latest version of this program");

        jButton1.setText("Open the Trac Bug Report Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(noticeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyButton)
                    .addComponent(jButton1))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        Clipboard clipboard = getToolkit().getSystemClipboard();
        String errorText = errorTextPane.getText();

        StringSelection fieldContent = new StringSelection(errorText);
        clipboard.setContents(fieldContent, this);
    }//GEN-LAST:event_copyButtonActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String url = "http://battlehub.darkstars.co.uk/trac/newticket?type=defect";
    if(username != null){
        if(username.trim().equals("")==false){
            url += "&reporter="+username.trim();
        }
    }
    BrowserLauncher.openURL(url);
}//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        //        new CErrorWindow().setVisible(true);
        //    }
        //});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyButton;
    private javax.swing.JTextPane errorTextPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noticeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership( Clipboard clipboard, Transferable contents ) {
        // do nothing
    }
    
}
