/*
 * LMain.java
 *
 * Created on 22 May 2006, 18:44
 */

package jlobby;
import com.sun.org.apache.bcel.internal.classfile.JavaClass;
import java.io.*;
import java.net.*;
import javax.swing.ImageIcon;
import jlobby.JLoginPanel;
import org.w3c.dom.*;

import java.util.*;
import java.util.regex.*;
import java.util.concurrent.*;

/**
 *
 * @author  AF
 */

class jTimerTask extends TimerTask {
    public LMain LM;
    jTimerTask(LMain L){
        LM = L;
    }
    public void run() {
        //LM.timerdo = true;
        JEvent e = new JEvent();
        e.data = new String[1];
        e.data[0] = "TIMER";
        LM.NewEvent(e);
    }
}

class UpdateTask extends TimerTask {
    public LMain LM;
    UpdateTask(LMain L){
        LM = L;
    }
    public void run() {
        LM.Update();
    }
}


public class LMain extends java.awt.Frame {
    public java.awt.Point origin= new java.awt.Point();
    public boolean nextvalidate = false;
    public boolean timerdo;
    /** Creates new form LMain */
    public LMain() {
        lobby_a_gogo = false;
        initComponents();
        playermanager = new JPlayers(this);
        Battle=new JBattle(this);
    }
    public void start(){
        setVisible(true);
        new Timer().schedule(new jTimerTask(this),
                1000,        //initial delay
                10000);  //subsequent rate
        new Timer().schedule(new UpdateTask(this),
                10,        //initial delay
                30);  //subsequent rate
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setFont(new java.awt.Font("Arial", 0, 12));
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setTitle("Apex");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(1.0F);
        jPanel2.setAlignmentY(1.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 10, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("_");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 10, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AF Lobby");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 30));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 840, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 570));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        java.awt.Point p = getLocation();
        setLocation(
        p.x + evt.getX() - origin.x, 
        p.y + evt.getY() - origin.y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        origin.x = evt.getX();
        origin.y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        java.awt.Point p = getLocation();
        setLocation(
        p.x + evt.getX() - origin.x, 
        p.y + evt.getY() - origin.y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        origin.x = evt.getX();
        origin.y = evt.getY();
        this.repaint();
    }//GEN-LAST:event_formMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
        //
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
        JLoginPanel LP = new JLoginPanel(this);
        AddView(LP,true);
        JChannelView CV = new JChannelView(this);
        AddView(CV,false);
    }//GEN-LAST:event_formWindowOpened

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    public void Update(){
        ProcessEvents();
        if(views.isEmpty()==false){
            Iterator<JView> i = views.iterator();
            while(i.hasNext()){
                JView n = i.next();
                n.Update();
            }
        }
        Iterator<JChannelWindow> i = channels.iterator();
        while(i.hasNext()){
            JChannelWindow j = i.next();
            j.Update();
        }
        if(nextvalidate == true){
            jPanel1.validate();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMain().setVisible(true);
            }
        });
    }
    public JBattle Battle;
    public Vector<JChannelWindow> channels = new Vector<JChannelWindow>();
    public ArrayList<String> joined = new ArrayList<String>();
    public ArrayList<JEvent> GUIeventqueue = new ArrayList<JEvent>();
    public ArrayList<JEvent> eventqueue = new ArrayList<JEvent>();
    public void NewEvent(JEvent e){
        eventqueue.add(e);
    }
    public void NewGUIEvent(JEvent e){
        GUIeventqueue.add(e);
    }
    public void ProcessEvents(){
        ArrayList<JView> vtemp = new ArrayList<JView>();
        vtemp.addAll(views);
        if(eventqueue.isEmpty()==false){
            ArrayList<JEvent> temp = new ArrayList<JEvent>();
            temp.addAll(eventqueue);
            eventqueue.clear();
            
            Iterator<JEvent> k = temp.iterator();
            while(k.hasNext()==true){
                JEvent e = k.next();
                if(e.data[0].equalsIgnoreCase("JOIN")){
                    // create a new channel object
                    JChannelWindow ch = new JChannelWindow();
                    ch.Init(this,e.data[1],e.connection);
                    ch.setVisible(true);
                    joined.add(e.data[1]);
                    channels.add(ch);
                }else if(e.data[0].equalsIgnoreCase("LEFTCHANNEL")){
                    // remove the channel!
                    joined.remove(e.data[1]);
                    Iterator<JChannelWindow> q = channels.iterator();
                    while(q.hasNext()){
                        JChannelWindow j = q.next();
                        if(j.Channel.equalsIgnoreCase(e.data[1])){
                            j.setVisible(false);
                            q.remove();
                            return;
                        }
                    }
                }
                if(channels.isEmpty()==false){
                    Iterator<JChannelWindow> p = channels.iterator();
                    while(p.hasNext()){
                        JChannelWindow j = p.next();
                        j.NewEvent(e);
                    }
                }
                connection.traffic.add("got event " + Misc.makeSentence(e.data,0));
                connection.NewEvent(e);
                Iterator<JView> i = vtemp.iterator();
                while(i.hasNext()){
                    JView n = i.next();
                    n.NewEvent(e);
                }
                playermanager.NewEvent(e);
                
            }
        }
        if(GUIeventqueue.isEmpty()==false){
            ArrayList<JEvent> temp2 = new ArrayList<JEvent>();
            temp2.addAll(GUIeventqueue);
            GUIeventqueue.clear();
            ArrayList<JView> temp3 = new ArrayList<JView>();
            temp3.addAll(views);
            Iterator<JEvent> q = temp2.iterator();
            while(q.hasNext()==true){
                JEvent e = q.next();
                connection.traffic.add("got GUI event " + Misc.makeSentence(e.data,0));
                connection.NewEvent(e);
                if(e.data[0].equalsIgnoreCase("JLOGOUT")){
                    SetFocus("LoginPanel");
                }
                if(channels.isEmpty()==false){
                    Iterator<JChannelWindow> p = channels.iterator();
                    while(p.hasNext()){
                        JChannelWindow j = p.next();
                        j.NewEvent(e);
                    }
                }
                Iterator<JView> i = vtemp.iterator();
                while(i.hasNext()){
                    JView n = i.next();
                    n.NewGUIEvent(e);
                }
                playermanager.NewGUIEvent(e);
            }
        }
    }
    
    public void AddView(JView v,boolean setfocus){
        //
        v.setVisible(false);
        jPanel1.add(v);
        views.add(v);
        DoValidate();
        if(setfocus == true){
            SetFocus(v);
        }
    }

    public void SetFocus(JView v){
        v.setVisible(true);
        int n = jPanel1.getComponentZOrder(v);
        jPanel1.setComponentZOrder(v,0);
       /* Iterator<JView> i = views.iterator();
        while(i.hasNext()){
            JView n =  i.next();
            if(n == v){
                v.setVisible(true);
            }else{
                v.setVisible(false);
            }
        }*/
        DoValidate();
    }
    public void SetFocus(String s){
        //v.setVisible(true);
        Iterator<JView> i = views.iterator();
        while(i.hasNext()){
            JView n =  i.next();
            if(n.Title.equalsIgnoreCase(s)){
                n.setVisible(true);
                jPanel1.setComponentZOrder(n,0);
                return;
            }
        }
        DoValidate();
    }
    
    public void DoValidate(){
        nextvalidate = true;
    }

    public JPlayers playermanager;
    public JConnection connection = new JConnection(this);
    public ArrayList<JView> views = new ArrayList<JView>();
    public boolean lobby_a_gogo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
