// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_MPSETTINGS_H
#define GUI_MPSETTINGS_H

// begin wxGlade: ::dependencies
// end wxGlade


class gui_mpSettings: public wxDialog {
public:
    // begin wxGlade: gui_mpSettings::ids
    // end wxGlade

    gui_mpSettings(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: gui_mpSettings::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_mpSettings::attributes
    wxStaticText* label_mpSettings_detail_treeViewDist;
    wxSlider* slider_mpSettings_detail_treeViewDist;
    wxStaticText* label_mpSettings_detail_terrainDetail;
    wxSlider* slider_mpSettings_detail_terrainDetail;
    wxStaticText* label_mpSettings_detail_unitDetailDist;
    wxSlider* slider_mpSettings_detail_unitDetailDist;
    wxStaticText* label_mpSettings_detail_grassDetail;
    wxSlider* slider_mpSettings_detail_grassDetail;
    wxStaticText* label_mpSettings_detail_particleLimit;
    wxSlider* slider_mpSettings_detail_particleLimit;
    wxStaticText* label_mpSettings_detail_maxSounds;
    wxSlider* slider_mpSettings_detail_maxSounds;
    wxCheckBox* checkbox_mpSettings_render_3DTrees;
    wxCheckBox* checkbox_mpSettings_render_highResClouds;
    wxCheckBox* checkbox_mpSettings_render_dynamicClouds;
    wxCheckBox* checkbox_mpSettings_render_reflectiveWater;
    wxCheckBox* checkbox_mpSettings_render_fullScreen;
    wxCheckBox* checkbox_mpSettings_render_coloredElevation;
    wxCheckBox* checkbox_mpSettings_render_invertMouse;
    wxCheckBox* checkbox_mpSettings_render_shadows;
    wxRadioBox* radiobox_mpSettings_render_shadowMaps;
    wxRadioBox* radiobox_mpSettings_render_unitTextures;
    wxStaticText* label_mpSettings_basics_playerName;
    wxTextCtrl* text_mpSettings_basics_nameData;
    wxStaticText* label_mpSettings_basics_screenRes;
    wxChoice* choice_mpSettings_basics_screenResData;
    wxButton* button_mpSettings_basics_save;
    wxButton* button_mpSettings_basics_cancel;
    wxButton* button_mpSettings_basics_revertToDefaults;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_MPSETTINGS_H
