# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 02 Apr 2008 11:12:18 -0700
*               @ALL          8
start	@frontpage	2
start	@ALL	1
