<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: admin
 * Date: Thu, 10 Apr 2008 15:23:48 -0700
 */

$conf['title'] = 'Spring Engine';
$conf['basedir'] = '/wiki/';
$conf['baseurl'] = 'http://newspring.darkstars.co.uk';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['gzip_output'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
