/*
 * JTraffic.java
 *
 * Created on 29 May 2006, 14:57
 */

package aflobby;

import aflobby.UI.CUISettings;
import javax.swing.SwingUtilities;

/**
 *
 * @author  AF
 */

public class JTraffic extends javax.swing.JFrame {
    /**
     * A reference to the current connection class. This is used to send raw
     * protocol data from the textbox. It is initialized in the call to Init()
     */
    public CConnection jc = null;

    /**
     * Creates a JTraffic form and initializes its UI components.
     * 
     * Call Init() afterwards or sending data usign the window will cause a null
     * pointer exception at runtime.
     */
    public JTraffic () {
        initComponents ();
    }
    /**
     * Initializes the traffic windows logic
     * @param c - the active connection class
     */
    public void Init (CConnection c){
        jc = c;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Raw Traffic");
        setIconImage(CUISettings.GetWindowIcon());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+3));
        jLabel1.setText("Raw Protocol Traffic");

        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setDoubleBuffered(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(415, 415, 415))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jTextField1});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Runnable doWorkRunnable = new Runnable () {
            public void run () {
                String n = jTextField1.getText ();
                jc.SendLine (n);
                add (n);
                jTextField1.setText ("");
            }
            
        };
        SwingUtilities.invokeLater (doWorkRunnable);
    }//GEN-LAST:event_jButton1MousePressed
    
    /**
     * Appends a new comamnd to the traffic window text. Use this to add traffic
     * as its recieved for display to the user.
     * 
     * @param s - the commands to be apended to the traffic view
     */
    public void add (String s){
        final String t = s;
        Runnable doWorkRunnable = new Runnable () {
            public void run () {
                if(jTextArea1.isShowing ()){
                    jTextArea1.append (t+"\n");
                    jTextArea1.setCaretPosition (jTextArea1.getText ().length ());
                }
            }
        };
        SwingUtilities.invokeLater (doWorkRunnable);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
