// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_LOBBY_H
#define GUI_LOBBY_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
#include <wx/notebook.h>
// end wxGlade


class gui_lobby: public wxFrame {
public:
    // begin wxGlade: gui_lobby::ids
    // end wxGlade

    gui_lobby(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: gui_lobby::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_lobby::attributes
    wxMenuBar* menubar_lobby;
    wxToolBar* toolbar_lobby;
    wxListCtrl* list_lobby_1_games;
    wxTextCtrl* text_lobby_1_chatArea;
    wxListBox* listbox_lobby_1_people;
    wxTextCtrl* text_lobby_1_chatBox;
    wxButton* button_lobby_1_send;
    wxButton* button_lobby_1_clear;
    wxPanel* panel_lobby_1;
    wxNotebook* notebook_lobby_main;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_LOBBY_H
