// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_CONNECT_H
#define GUI_CONNECT_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


class gui_connect: public wxDialog {
public:
    // begin wxGlade: gui_connect::ids
    // end wxGlade

    gui_connect(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: gui_connect::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_connect::attributes
    wxStaticText* label_connect_name;
    wxTextCtrl* text_connect_nameData;
    wxStaticText* label_connect_password;
    wxTextCtrl* text_connect_passwordData;
    wxCheckBox* checkbox_connect_rememberLogin;
    wxStaticText* label_connect_rememberLogin;
    wxButton* button_connect_login;
    wxButton* button_connect_register;
    wxStaticLine* static_line_1;
    wxTextCtrl* text_connect_helpBox;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_CONNECT_H
