// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include "gui_connect.h"


gui_connect::gui_connect(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: gui_connect::gui_connect
    label_connect_name = new wxStaticText(this, -1, wxT("Name: "), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    text_connect_nameData = new wxTextCtrl(this, 201, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_PROCESS_TAB);
    label_connect_password = new wxStaticText(this, -1, wxT("Password: "));
    text_connect_passwordData = new wxTextCtrl(this, 202, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_PROCESS_TAB|wxTE_PASSWORD);
    checkbox_connect_rememberLogin = new wxCheckBox(this, -1, wxT(""));
    label_connect_rememberLogin = new wxStaticText(this, -1, wxT("Remember login"));
    button_connect_login = new wxButton(this, 101, wxT("Log In"));
    button_connect_register = new wxButton(this, 102, wxT("Register"));
    static_line_1 = new wxStaticLine(this, -1);
    text_connect_helpBox = new wxTextCtrl(this, -1, wxT("Enter your username and password to log into the Master Server.\n\nIf you do not have a username and password, enter your desired username and password, and hit the \"Register\" button.  This will register your nickname and send you to the Spring Lobby. "), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxTE_AUTO_URL);

    set_properties();
    do_layout();
    // end wxGlade
}


void gui_connect::set_properties()
{
    // begin wxGlade: gui_connect::set_properties
    SetTitle(wxT("Omni - Connect/Register"));
    wxIcon _icon;
    _icon.CopyFromBitmap(wxBitmap(wxT("resource/spring-redlogo.png"), wxBITMAP_TYPE_ANY));
    SetIcon(_icon);
    text_connect_nameData->SetMinSize(wxSize(100, 25));
    text_connect_passwordData->SetMinSize(wxSize(100, 25));
    checkbox_connect_rememberLogin->SetMinSize(wxSize(22, 21));
    button_connect_login->SetToolTip(wxT("Login with the username and password entered above"));
    button_connect_login->SetDefault();
    button_connect_register->SetToolTip(wxT("Register the username and password above and login"));
    text_connect_helpBox->SetMinSize(wxSize(275, 150));
    // end wxGlade
}


void gui_connect::do_layout()
{
    // begin wxGlade: gui_connect::do_layout
    wxFlexGridSizer* grid_connect_main = new wxFlexGridSizer(4, 3, 0, 0);
    wxBoxSizer* sizer_connect_helpBox = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* grid_connect_loginInfo = new wxGridSizer(6, 2, 3, 0);
    grid_connect_main->Add(10, 10, 0, 0, 0);
    grid_connect_main->Add(200, 10, 0, 0, 0);
    grid_connect_main->Add(10, 10, 0, 0, 0);
    grid_connect_main->Add(10, 100, 0, 0, 0);
    grid_connect_loginInfo->Add(label_connect_name, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    grid_connect_loginInfo->Add(text_connect_nameData, 0, wxFIXED_MINSIZE, 0);
    grid_connect_loginInfo->Add(label_connect_password, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    grid_connect_loginInfo->Add(text_connect_passwordData, 0, wxFIXED_MINSIZE, 0);
    grid_connect_loginInfo->Add(checkbox_connect_rememberLogin, 0, wxALIGN_RIGHT|wxALIGN_CENTER_HORIZONTAL, 0);
    grid_connect_loginInfo->Add(label_connect_rememberLogin, 0, 0, 0);
    grid_connect_loginInfo->Add(button_connect_login, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    grid_connect_loginInfo->Add(button_connect_register, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    grid_connect_main->Add(grid_connect_loginInfo, 0, wxALIGN_CENTER_HORIZONTAL|wxSHAPED, 0);
    grid_connect_main->Add(10, 100, 0, 0, 0);
    grid_connect_main->Add(10, 100, 0, 0, 0);
    sizer_connect_helpBox->Add(20, 5, 0, 0, 0);
    sizer_connect_helpBox->Add(static_line_1, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_connect_helpBox->Add(20, 8, 0, 0, 0);
    sizer_connect_helpBox->Add(text_connect_helpBox, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    grid_connect_main->Add(sizer_connect_helpBox, 2, wxEXPAND, 0);
    grid_connect_main->Add(10, 100, 0, 0, 0);
    grid_connect_main->Add(10, 10, 0, 0, 0);
    grid_connect_main->Add(200, 10, 0, 0, 0);
    grid_connect_main->Add(10, 10, 0, 0, 0);
    SetAutoLayout(true);
    SetSizer(grid_connect_main);
    grid_connect_main->Fit(this);
    grid_connect_main->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

