/*
 * WarningWindow.java
 *
 * Created on 23 April 2007, 14:24
 */

package aflobby.UI;

import aflobby.*;
import aflobby.helpers.BrowserLauncher;
import java.awt.Color;
import java.awt.Point;
import java.net.URL;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author  Tom
 */
public class WarningWindow extends javax.swing.JFrame {
    Point origin = new Point ();
    /**
     * Creates new form WarningWindow
     * @param data
     * @param Title 
     */
    public WarningWindow (final String data, final String Title) {
        initComponents ();
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                jEditorPane1.setText (data);
                jEditorPane1.setCaretPosition (0);
                setTitle (Title);
            }
        });
        
    }
    
    public WarningWindow (final String data, final String Title,final boolean alwaysontop) {
        
        initComponents ();
        
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                jEditorPane1.setText (data);
                jEditorPane1.setCaretPosition (0);
                setTitle (Title);
                setAlwaysOnTop (alwaysontop);
            }
        });
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JNI error");
        setIconImage(CUISettings.GetWindowIcon());
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(95, 146, 213));
        jScrollPane1.setBorder(null);

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jEditorPane1HyperlinkUpdate (javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEditorPane1HyperlinkUpdate
        if(evt.getEventType () == HyperlinkEvent.EventType.ACTIVATED){
            //
            URL r = evt.getURL ();
            if(r!=null){
                String u = r.toExternalForm ();
                u = u.replaceAll (" //","");
                BrowserLauncher.openURL (u);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jEditorPane1HyperlinkUpdate
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
