// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include "gui_channel.h"


gui_channel::gui_channel(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: gui_channel::gui_channel
    const wxString list_channel_channels_choices[] = {
        
    };
    list_channel_channels = new wxListBox(this, -1, wxDefaultPosition, wxDefaultSize, 0, list_channel_channels_choices, wxLB_SINGLE);
    text_channel_channel = new wxTextCtrl(this, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    button_channel_join = new wxButton(this, -1, wxT("Join"));

    set_properties();
    do_layout();
    // end wxGlade
}


void gui_channel::set_properties()
{
    // begin wxGlade: gui_channel::set_properties
    SetTitle(wxT("Omni - Join Channel"));
    wxIcon _icon;
    _icon.CopyFromBitmap(wxBitmap(wxT("resource/spring-redlogo.png"), wxBITMAP_TYPE_ANY));
    SetIcon(_icon);
    SetSize(wxSize(429, 265));
    list_channel_channels->SetToolTip(wxT("Double-click a channel to join it"));
    button_channel_join->SetDefault();
    // end wxGlade
}


void gui_channel::do_layout()
{
    // begin wxGlade: gui_channel::do_layout
    wxFlexGridSizer* grid_channel_main = new wxFlexGridSizer(5, 3, 0, 0);
    wxFlexGridSizer* sizer_10 = new wxFlexGridSizer(1, 2, 0, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(50, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(list_channel_channels, 0, wxEXPAND, 0);
    grid_channel_main->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(50, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    sizer_10->Add(text_channel_channel, 0, wxEXPAND, 0);
    sizer_10->Add(button_channel_join, 0, 0, 0);
    sizer_10->AddGrowableCol(0);
    grid_channel_main->Add(sizer_10, 1, wxEXPAND, 0);
    grid_channel_main->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(50, 10, 0, wxADJUST_MINSIZE, 0);
    grid_channel_main->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(grid_channel_main);
    grid_channel_main->AddGrowableRow(1);
    grid_channel_main->AddGrowableCol(1);
    Layout();
    Centre();
    // end wxGlade
}

