-- Some example SQL for the website, intended for an installation of the site on you own system.
-- Note that this excludes the mediawiki and phpbb2 data, only the site translation data can be found here at this moment.

-- phpMyAdmin SQL Dump
-- version 2.9.1.1-Debian-2ubuntu1
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generatie Tijd: 25 Jun 2007 om 19:07
-- Server versie: 5.0.38
-- PHP Versie: 5.2.1
-- 
-- Database: `spring`
-- 

-- --------------------------------------------------------

-- 
-- Tabel structuur voor tabel `site_language`
-- 

CREATE TABLE `site_language` (
  `language` varchar(15) NOT NULL,
  `id` int(11) NOT NULL auto_increment,
  `user` varchar(50) default NULL,
  `date_time` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `version_major` int(4) NOT NULL,
  `version_minor` int(4) NOT NULL,
  `header` text,
  `index` text,
  `news` text,
  `development` text,
  `download` text,
  `about` text,
  PRIMARY KEY  (`language`,`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

-- 
-- Gegevens worden uitgevoerd voor tabel `site_language`
-- 

INSERT INTO `site_language` (`language`, `id`, `user`, `date_time`, `version_major`, `version_minor`, `header`, `index`, `news`, `development`, `download`, `about`) VALUES 
('empty', 1, NULL, '2007-06-25 19:00:52', 0, 0, '', '', '', '', '', ''),
('development', 8, 'Tim Blokdijk', '2007-06-25 19:01:57', 1, 0, NULL, 'download_title=STR%"Download"&END%download_text=STR%"<A HREF=\\"download\\">Link to downlaod page</A> version information, date of release and possibly a codename."&END%highlight_title=STR%"Highlight"&END%highlight_in_english=STR%"(in English) used for non-english translations to make clear that this section is not translated."&END%introduction_title=STR%"Introduction"&END%introduction_text=STR%"What is Spring? FILLER --- Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas nonummy urna sit amet erat. Vivamus ut tortor at orci venenatis volutpat. Nulla facilisi. Cras eget mauris. Cras faucibus. Quisque scelerisque, purus sit amet pulvinar laoreet, ante dui venenatis mauris, id eleifend nibh turpis at lectus. Integer varius. Nulla facilisi. Donec vestibulum. Duis arcu diam, bibendum quis, sodales eu, fringilla laoreet, augue. Ut nec turpis. Ut tristique ante et felis. Quisque libero mi, ultricies sit amet, blandit vitae, eleifend sit amet, ligula. Mauris ac velit ac neque dictum euismod. Sed quam. Sed massa massa, vestibulum non, faucibus eu, rutrum a, lacus. Integer in ligula. Nam sit amet libero eget enim dignissim iaculis. Mauris nunc sem, pulvinar eu, faucibus et, auctor at, tortor. Nulla dapibus dolor sed lorem. --- FILLER"&END%features_title=STR%"Spring Features"&END%features_text=STR%"Feature text for non-javascript/non-flash browsers."&END%features_text_flash_enabled=STR%"Feature text for javascript enabled and flash installed browsers."&END%feature1=STR%"Feature 1 description"&END%feature2=STR%"Feature 2 description"&END%feature3=STR%"Feature 3 description"&END%feature4=STR%"Feature 4 description"&END%feature5=STR%"Feature 5 description"&END%feature6=STR%"Feature 6 description"&END%info_title=STR%"Playing Spring"&END%info_text1=STR%"Text for the more basic information links."&END%info_text2=STR%"Text for the more involved players."&END%info_getting_strated=STR%"Getting Started (installation) (in english)"&END%info_player_guide=STR%"Player Guide (how to play) (in english)"&END%info_news=STR%"Spring News"&END%info_messageboard=STR%"Spring Messageboard"&END%info_wiki=STR%"Spring Wiki"&END%info_league=STR%"Spring Leage"&END%screenshots_more=STR%"More Screenshots..."&END%com_news_title=STR%"Community News"&END%com_news_in_english=STR%"(in English)"&END%pro_news_title=STR%"Project News"&END%pro_news_in_english=STR%"(in English)"&END%', NULL, NULL, NULL, NULL),
('development', 7, 'Tim Blokdijk', '2007-06-25 19:02:08', 1, 0, 'news=STR%"News"&END%news_tooltip=STR%"Tooltip for link to news page"&END%wiki=STR%"Wiki"&END%wiki_tooltip=STR%"Tooltip for link to wiki"&END%messageboard=STR%"Messageboard"&END%messageboard_tooltip=STR%"Tooltip for link to messageboard"&END%about=STR%"About us"&END%about_tooltip=STR%"Tooltip for link to about"&END%development=STR%"Development"&END%development_tooltip=STR%"Tooltip for link to development page"&END%language=STR%"Language"&END%language_tooltip=STR%"Tooltip for language button when JavaScript is disabled."&END%theme=STR%"Theme"&END%theme_tooltip=STR%"Tooltip for theme button when JavaScript is disabled."&END%mission_text=STR%"Enjoy taking <ACRONYM TITLE=\\"Real Time Strategy\\">RTS</ACRONYM> gaming to the highest level."&END%mission_name=STR%"SPRING"&END%', NULL, NULL, NULL, NULL, NULL),
('development', 9, 'Tim Blokdijk', '2007-06-19 16:48:35', 1, 0, NULL, NULL, NULL, 'participate_title=STR%"Participate"&END%participate_text=STR%"Spring needs skilled people that like to develop Spring. FILLER --- Sed at tellus sit amet odio bibendum hendrerit. Integer sapien elit, dapibus ut, adipiscing non, ullamcorper at, erat. Nullam quis nibh vel lorem aliquam tempus. Aenean vehicula, leo eget eleifend semper, est quam volutpat libero, sed bibendum velit felis a lacus. Maecenas ornare. In volutpat mauris vitae nibh. In vehicula egestas leo. Suspendisse sed libero. Aenean vitae risus in massa aliquam sodales. Aenean eu est. Nam bibendum pede vitae pede. --- FILLER"&END%content_title=STR%"Content"&END%content_text=STR%"List of all the content tasks."&END%code_title=STR%"Code"&END%code_text=STR%"List of all the code tasks."&END%', NULL, NULL),
('dutch', 6, 'Tim Blokdijk', '2007-06-19 18:13:10', 1, 0, 'news=STR%"Nieuws"&END%news_tooltip=STR%"De nieuws pagina."&END%wiki=STR%"Wiki"&END%wiki_tooltip=STR%"De wiki met een wereld aan Spring informatie."&END%messageboard=STR%"Berichtenbord"&END%messageboard_tooltip=STR%"De voornaamste manier van communiceren voor dit project."&END%about=STR%"Over ons"&END%about_tooltip=STR%"De mensen achter en de historie van dit project."&END%development=STR%"Ontwikkeling"&END%development_tooltip=STR%"Meer informatie over meehelpen aan de ontwikkeling van Spring."&END%language=STR%"Talen"&END%language_tooltip=STR%"Selecteer een taal naar keuze."&END%theme=STR%"Thema"&END%theme_tooltip=STR%"Kies een ander thema."&END%mission_text=STR%"Geniet van <ACRONYM TITLE=\\"Real Time Strategy\\">RTS</ACRONYM> gaming naar het hoogste niveau te tillen."&END%mission_name=STR%"SPRING"&END%', NULL, NULL, NULL, NULL, NULL),
('dutch', 10, 'Tim Blokdijk', '2007-06-19 19:15:51', 1, 0, NULL, 'download_title=STR%"Download"&END%download_text=STR%"Download Spring versie 0.74b3 van de <A HREF=\\"download\\">download pagina</A>."&END%highlight_title=STR%"Uitgelicht"&END%highlight_in_english=STR%"(in het Engels)"&END%introduction_title=STR%"Introductie"&END%introduction_text=STR%"Hallo en welkom op de pagina van het Spring project, Spring is een open source RTS spel dat uit veel verschillende \\"deel-spellen\\" bestaat waarmee je kan spelen. Je hebt om te beginnen de nieuwste Spring versie nodig wat de \\"engine\\" en een basis aan spel materiaal bevat, genoeg om mee te kunnen beginnen. Later kan je deze basis aanvullen met materiaal dat beschikbaar is op o.a. http://spring.unknown-files.com. Nieuwe spelers wordt aangeraden om de \\"Hoe te beginnen\\" uitleg te lezen hieronder.\r\n\r\nAls je wil meewerken aan de ontwikkeling van Spring dan ben je natuurlijk van harte welkom, Spring is in principe open source dus je kan op allerlei gebieden interessante dingen doen van het programmeren aan de engine, deze site vertalen, kunstmatige intelligentie, of b.v. de werelden waarin wordt gespeeld maken."&END%features_title=STR%"Spring Eigenschappen"&END%features_text=STR%"Video\\''s zijn beschikbaar als je een flash speler hebt geinstaleerd en JavaScript staat ingeschakeld."&END%features_text_flash_enabled=STR%"Klik op een eigenschap voor een korte video."&END%feature1=STR%"Grootte veldslagen."&END%feature2=STR%"Zware explosies."&END%feature3=STR%"Transformeerbaar terein."&END%feature4=STR%"Water effecten."&END%feature5=STR%"Natuurkunde."&END%feature6=STR%"Vanuit het 1ste perspectief."&END%info_title=STR%"Spring spelen"&END%info_text1=STR%"De volgende informatie kan je op weg helpen bij het spelen van spring."&END%info_text2=STR%"Deze links zijn interesant als je actief wil deelnemen aan deze gemeenschap."&END%info_getting_strated=STR%"Hoe te beginnen (instalatie) - in het Engels"&END%info_player_guide=STR%"Spel uitleg (hoe je moet spelen) - in het Engels"&END%info_news=STR%"Spring Nieuws"&END%info_messageboard=STR%"Spring Berichtenbord"&END%info_wiki=STR%"Spring Wiki"&END%info_league=STR%"Spring Toernooi"&END%screenshots_more=STR%"Meer Screenshots"&END%com_news_title=STR%"Algemeen Nieuws"&END%com_news_in_english=STR%"(in het Engels)"&END%pro_news_title=STR%"Project Nieuws"&END%pro_news_in_english=STR%"(in het Engels)"&END%', NULL, NULL, NULL, NULL),
('development', 10, 'Tim Blokdijk', '2007-06-21 21:40:56', 1, 0, NULL, NULL, 'news_into_title=STR%"Spring news page"&END%news_into_text=STR%"This is the Spring news page, here you can find an RSS feed, all the news postings and ??.\r\nHave lots of fun and don\\''t kill anybody!\r\n\r\nStill need to make a good development text for this section."&END%com_news_title=STR%"Community News"&END%com_news_in_english=STR%"(in English)"&END%pro_news_title=STR%"Project News"&END%pro_news_in_english=STR%"(in English)"&END%', NULL, NULL, NULL),
('english', 10, 'Tim Blokdijk', '2007-06-21 21:49:42', 1, 0, NULL, NULL, 'news_into_title=STR%"Spring news page"&END%news_into_text=STR%"This is the Spring news page, here you can find an RSS feed, all the news postings and ??.\r\n\r\nHave lots of fun and don\\''t kill anybody!\r\n\r\nCommunity News is freely editable by anybody with a messageboard account.\r\nProject News is only editable by Spring developers and has the more \\"official\\" news."&END%com_news_title=STR%"Community News"&END%com_news_in_english=STR%"TODO: Make dynamic"&END%pro_news_title=STR%"Project News"&END%pro_news_in_english=STR%"TODO: Make dynamic"&END%', NULL, NULL, NULL),
('development', 11, 'Tim Blokdijk', '2007-06-21 22:32:58', 1, 0, NULL, NULL, NULL, NULL, NULL, 'project_description_title=STR%"The Spring Project"&END%project_description_text=STR%"Spring is an Open source ... LOADS of text here about Spring, the way it\\''s set-up, history, Total Annihilation, bla, bla, ect. ect.\r\n\r\nThe roots of the project lie with the &quot;Total Annihilation&quot;&trade; gaming community which is around 10 years old. The Spring project itself strated in 2004 with its code released under the GPL, \r\n\r\nContent\r\nCode\r\nAdmins\r\nRetired contributors\r\n\r\nAll the people that maintain this great athmosphere within our communety."&END%history_title=STR%""&END%history_text=STR%""&END%developers_title=STR%"Spring Developers"&END%developers_in_english=STR%"(in English)"&END%'),
('english', 11, 'Tim Blokdijk', '2007-06-21 22:36:50', 1, 0, NULL, NULL, NULL, NULL, NULL, 'project_description_title=STR%"About the Spring Project"&END%project_description_text=STR%"Spring is an Open source ... LOADS of text here about Spring, the way it\\''s set-up, history, Total Annihilation, bla, bla, ect. ect.\r\n\r\nThe roots of the project lie with the &quot;Total Annihilation&quot;&trade; gaming community which is around 10 years old. The Spring project itself strated in 2004 with its code released under the GPL,\r\n\r\nContent\r\nCode\r\nAdmins\r\nRetired contributors\r\n\r\nAll the people that maintain this great athmosphere within our communety."&END%history_title=STR%""&END%history_text=STR%""&END%developers_title=STR%"Spring Developers"&END%developers_in_english=STR%""&END%'),
('english', 12, 'Tim Blokdijk', '2007-06-25 19:02:21', 1, 0, NULL, NULL, NULL, 'participate_title=STR%"Participate"&END%participate_text=STR%"We are a buch of people from around the world - love RTS gaming - we develop Spring because we like to - we do this mostly on an \\"Open Source\\" basis so everybody can help develop the code and content that we collectivly play. - The developemnt process is split in code and content development both are heavely interlinked so the distinction is not that hard, the main diffrence is that you need other tools and skills.\r\n\r\nBug tracker, feature request sub-forum ect."&END%content_title=STR%"Content"&END%content_text=STR%"<U>Unit developement</U><br />\r\nWork on the units you can build and command, you need modeling, animation, texturing and scripting skills to make fully functional units.<br />\r\n<U>Mapping</U><br />\r\nMapping is making the worlds where battles can be fought, it\\''s also possible to make missions.<br />\r\n<U>Writing</U><br />\r\nWe need documentation, story-lines, reviews, translations for this site and just generaly nice people to build our communety on."&END%code_title=STR%"Code"&END%code_text=STR%"<U>Engine development</U><br />\r\nThe Spring engine is the main dish and it needs a lot of work, if you know C++ take a look at it.<br />\r\n<U>Tool development</U><br />\r\nLobby and others. We have a few app\\''s that are used for unit and map developement and also these need work.<br />\r\n<U>Artificial Inteligence</U><br />\r\nGeneraly we can still beat the AI\\''s..<br />\r\n<U>Site development</U><br />\r\nLike to code up some new features for this site? Have you found a bug in it? The code is availeble."&END%', NULL, NULL),
('development', 12, 'Tim Blokdijk', '2007-06-22 00:16:27', 2, 0, 'news=STR%"News"&END%news_tooltip=STR%"Tooltip for link to news page"&END%wiki=STR%"Wiki"&END%wiki_tooltip=STR%"Tooltip for link to wiki"&END%messageboard=STR%"Messageboard"&END%messageboard_tooltip=STR%"Tooltip for link to messageboard"&END%about=STR%"About us"&END%about_tooltip=STR%"Tooltip for link to about"&END%development=STR%"Development"&END%development_tooltip=STR%"Tooltip for link to development page"&END%language=STR%"Language"&END%language_tooltip=STR%"Tooltip for language button when JavaScript is disabled."&END%theme=STR%"Theme"&END%theme_tooltip=STR%"Tooltip for theme button when JavaScript is disabled."&END%mission_text=STR%"Enjoy taking <ACRONYM TITLE=\\"Real Time Strategy\\">RTS</ACRONYM> gaming to the highest level."&END%mission_name=STR%"SPRING"&END%', NULL, NULL, NULL, NULL, NULL),
('english', 14, 'Tim Blokdijk', '2007-06-22 00:17:18', 2, 0, 'news=STR%"News"&END%news_tooltip=STR%"Spring\\''s news page."&END%wiki=STR%"Wiki"&END%wiki_tooltip=STR%"A world of user contributed Spring knowledge."&END%messageboard=STR%"Messageboard"&END%messageboard_tooltip=STR%"The main form of communication for the Spring project."&END%about=STR%"About us"&END%about_tooltip=STR%"The project background and its core developers."&END%development=STR%"Development"&END%development_tooltip=STR%"General information about Spring\\''s development."&END%language=STR%"Language"&END%language_tooltip=STR%"Click on the language of your choice."&END%theme=STR%"Theme"&END%theme_tooltip=STR%"Select a theme for this site."&END%mission_text=STR%"Enjoy taking <ACRONYM TITLE=\\"Real Time Strategy\\">RTS</ACRONYM> gaming to the highest level."&END%mission_name=STR%"SPRING"&END%', NULL, NULL, NULL, NULL, NULL),
('german', 2, 'Tim Blokdijk', '2007-06-22 00:43:55', 2, 0, 'news=STR%"News"&END%news_tooltip=STR%"Vier Tote, brennende HÃ¤user und Ãœberschwemmungen"&END%wiki=STR%"Wiki"&END%wiki_tooltip=STR%"Unser Wiki"&END%messageboard=STR%"Berichteboard"&END%messageboard_tooltip=STR%"Unser webforum"&END%about=STR%"Ãœber ons"&END%about_tooltip=STR%"Wir mÃ¶gen prahlen"&END%development=STR%"Entwicklung"&END%development_tooltip=STR%"Allgemeine Entwicklungsinformationen"&END%language=STR%"Sprache"&END%language_tooltip=STR%"WÃ¤hlen Sie eine Sprache"&END%theme=STR%"Thema"&END%theme_tooltip=STR%"WÃ¤hlen Sie ein Thema aus"&END%mission_text=STR%"GenieÃŸen Sie nehmend <ACRONYM TITLE=\\"Real Time Strategy\\">RTS</ACRONYM> Gaming zur hÃ¶chsten Ebene."&END%mission_name=STR%"SPRING"&END%', NULL, NULL, NULL, NULL, NULL),
('english', 15, 'Tim Blokdijk', '2007-06-25 19:06:48', 1, 0, NULL, 'download_title=STR%"Download"&END%download_text=STR%"Get Spring version 0.74b3 from the <A HREF=\\"download\\">download page</A>."&END%highlight_title=STR%"Highlight"&END%highlight_in_english=STR%"TODO: Make dynamic"&END%introduction_title=STR%"Introduction of the Game"&END%introduction_text=STR%"Hello and welcome to the world of Spring gaming. Spring is a open source RTS engine that features many different game universes to fight in. You need the latest Spring release which contains the core engine components and some content to play with. Later you can check out the many other universes that are available from http://spring.unknown-files.com. As a new player you should read the getting started guide below.<br />\r\n<br />\r\nIf you would like to involve yourself in the ongoing development process (code and/or content) then click on the development link in the menu. With spring you can work on the engine code iteself, the tools, this site, artificial intelligence, or the universes in which people play."&END%features_title=STR%"Spring Features"&END%features_text=STR%"Video\\''s are availeble if you have a flash player installed and JavaScript enabled."&END%features_text_flash_enabled=STR%"Click on a feature below for a short flash video."&END%feature1=STR%"Massive battles."&END%feature2=STR%"Cool explosions."&END%feature3=STR%"Deformable terain."&END%feature4=STR%"Water effects."&END%feature5=STR%"Phisics."&END%feature6=STR%"1st person control."&END%info_title=STR%"Playing Spring"&END%info_text1=STR%"The following information can help you on your way as a Spring player."&END%info_text2=STR%"Check out the following links if you like to be active in the community."&END%info_getting_strated=STR%"Getting Started (installation)"&END%info_player_guide=STR%"Player Guide (how to play)"&END%info_news=STR%"Spring News"&END%info_messageboard=STR%"Spring Messageboard"&END%info_wiki=STR%"Spring Wiki"&END%info_league=STR%"Spring League"&END%screenshots_more=STR%"More Screenshots"&END%com_news_title=STR%"Community News"&END%com_news_in_english=STR%"TODO: Make dynamic"&END%pro_news_title=STR%"Project News"&END%pro_news_in_english=STR%"TODO: Make dynamic"&END%', NULL, NULL, NULL, NULL);

