/*
 * CSplashScreen.java
 *
 * Created on 19 September 2006, 21:45
 */
package aflobby;

import aflobby.UI.CUserSettings;
import aflobby.UI.CView;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Shade
 */
public class CSplashScreen extends CView implements java.awt.event.MouseListener, ActionListener {

    /**
     * Creates new form CSplashScreen
     */
    public CSplashScreen(LMain L) {
        LM = L;
        Initialize();
        ValidatePanel();
        setTitle("Splash");
    }

    @Override
    public void Initialize() {
        initComponents();
        UserTitle = java.util.ResourceBundle.getBundle("aflobby/languages").getString("CSplashScreen.Welcome_Menu");
        new CUpdateChecker(update_label).start();
    }

    @Override
    public void ValidatePanel() {
        validate();
        LM.DoValidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        update_label = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setFont(new java.awt.Font("Arial", 0, 11));
        setMinimumSize(new java.awt.Dimension(840, 570));
        setPreferredSize(new java.awt.Dimension(840, 570));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("aflobby/languages"); // NOI18N
        jButton1.setText(bundle.getString("CSplashScreen.Log_Into_Lobby")); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 0), 1, true));
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(this);

        jButton2.setText(bundle.getString("CSplashScreen.Single_Player")); // NOI18N
        jButton2.setEnabled(CUserSettings.GetValue("singleplayer.command", "").equals("")==false);
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(72, 14));
        jButton2.addActionListener(this);

        jButton4.setText(bundle.getString("CSplashScreen.Watch_Replays")); // NOI18N
        jButton4.setEnabled(false);
        jButton4.setFocusPainted(false);

        jButton3.setText(bundle.getString("CSplashScreen.Settings")); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(72, 14));
        jButton3.addActionListener(this);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+13));
        jLabel1.setText(java.util.ResourceBundle.getBundle("aflobby/languages").getString("CSplashScreen.AFLobbyUpdatePrefix")+CUpdateChecker.AFLobbyVersion);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        update_label.setFont(update_label.getFont().deriveFont(update_label.getFont().getStyle() | java.awt.Font.BOLD, update_label.getFont().getSize()+5));
        update_label.setText("Checking darkstars.co.uk for updates");
        update_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton5.setText("Spring Settings");
        jButton5.setEnabled(CUserSettings.GetValue("settings.command", "").equals("")==false);
        jButton5.addActionListener(this);

        jButton6.setText("Report Bug/Request");
        jButton6.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(update_label, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(update_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton2) {
            CSplashScreen.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            CSplashScreen.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton5) {
            CSplashScreen.this.jButton5ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton6) {
            CSplashScreen.this.jButton6ActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jButton1) {
            CSplashScreen.this.jButton1MousePressed(evt);
        }
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jButton1) {
            CSplashScreen.this.jButton1MouseReleased(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        if (LM.ViewExists("LoginPanel") == false) {
            CLoginPanel LP = new CLoginPanel(LM);
            LM.AddView(LP, true);
        } else {
            LM.SetFocus("LoginPanel");
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CSettings c = new CSettings(LM, true);
        LM.AddView(c, true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String c = CUserSettings.GetValue("settings.command", "");
        if (c.equals("")) {
            return;
        } else {
            try {
                Runtime.getRuntime().exec(c);
            } catch (IOException ex) {
                Logger.getLogger(CSplashScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String c = CUserSettings.GetValue("singleplayer.command", "");
        if (c.equals("")) {
            return;
        } else {
            try {
                Runtime.getRuntime().exec(c);
            } catch (IOException ex) {
                Logger.getLogger(CSplashScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        aflobby.helpers.BrowserLauncher.openURL("http://mantis.darkstars.co.uk/bug_report_page.php");
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel update_label;
    // End of variables declaration//GEN-END:variables
}