# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sun Mar 12 15:08:06 2006

import wx

# begin wxGlade: dependencies
# end wxGlade

class gui_units(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: gui_units.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_units_currentName = wx.StaticText(self, -1, "Peewee")
        self.bitmap_units_currentPreview = wx.StaticBitmap(self, -1, wx.Bitmap("resource/pewee.png", wx.BITMAP_TYPE_ANY))
        self.checkbox_units_disabled = wx.CheckBox(self, 301, "Disable Unit")
        self.checkbox_units_limit = wx.CheckBox(self, 302, "Unit Limit")
        self.text_units_limitData = wx.TextCtrl(self, 201, "")
        self.button_units_update = wx.Button(self, -1, "Update")
        self.button_units_done = wx.Button(self, 101, "Done")
        self.button_units_revertToDefaults = wx.Button(self, 101, "Defaults")
        self.list_units_unitList = wx.ListCtrl(self, 901, style=wx.LC_REPORT|wx.LC_ICON|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: gui_units.__set_properties
        self.SetTitle("Disabled Units")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("resource/spring-redlogo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.label_units_currentName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_units_limitData.SetMinSize((80, 25))
        self.text_units_limitData.Enable(False)
        self.button_units_update.SetMinSize((100, 30))
        self.button_units_update.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_units_update.SetDefault()
        self.button_units_revertToDefaults.SetMinSize((70, 30))
        self.button_units_revertToDefaults.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.list_units_unitList.SetMinSize((300, 285))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: gui_units.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 5, 0, 0)
        grid_units_info = wx.FlexGridSizer(12, 1, 0, 0)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        grid_sizer_1.Add((130, 15), 0, 0, 0)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        grid_sizer_1.Add((210, 15), 0, 0, 0)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        grid_sizer_1.Add((15, 200), 0, 0, 0)
        grid_units_info.Add(self.label_units_currentName, 0, 0, 0)
        grid_units_info.Add((100, 15), 0, 0, 0)
        grid_units_info.Add(self.bitmap_units_currentPreview, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_units_info.Add((100, 15), 0, 0, 0)
        grid_units_info.Add(self.checkbox_units_disabled, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_units_info.Add((100, 15), 0, 0, 0)
        sizer_7.Add(self.checkbox_units_limit, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add((5, 20), 0, wx.FIXED_MINSIZE, 0)
        sizer_7.Add(self.text_units_limitData, 0, wx.FIXED_MINSIZE, 0)
        grid_units_info.Add(sizer_7, 1, wx.EXPAND, 0)
        grid_units_info.Add((100, 7), 0, 0, 0)
        grid_units_info.Add(self.button_units_update, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.FIXED_MINSIZE, 0)
        grid_units_info.Add((100, 15), 0, 0, 0)
        sizer_1.Add(self.button_units_done, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add((20, 20), 0, wx.FIXED_MINSIZE, 0)
        sizer_1.Add(self.button_units_revertToDefaults, 0, wx.FIXED_MINSIZE, 0)
        grid_units_info.Add(sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(grid_units_info, 1, wx.EXPAND, 0)
        grid_sizer_1.Add((15, 200), 0, 0, 0)
        grid_sizer_1.Add(self.list_units_unitList, 1, wx.FIXED_MINSIZE, 0)
        grid_sizer_1.Add((15, 200), 0, 0, 0)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        grid_sizer_1.Add((130, 15), 0, 0, 0)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        grid_sizer_1.Add((210, 15), 0, 0, 0)
        grid_sizer_1.Add((15, 15), 0, 0, 0)
        self.SetAutoLayout(True)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class gui_units


