#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4 on Sat Dec 17 12:42:48 2005

import wx
from gui_lobby import gui_lobby

class wxGUI(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        lobby = gui_lobby(None, -1, "")
        self.SetTopWindow(lobby)
        lobby.Show()
        return 1

# end of class wxGUI

if __name__ == "__main__":
    omni = wxGUI(0)
    omni.MainLoop()
