// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_HOST_H
#define GUI_HOST_H

// begin wxGlade: ::dependencies
// end wxGlade


class gui_host: public wxDialog {
public:
    // begin wxGlade: gui_host::ids
    // end wxGlade

    gui_host(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: gui_host::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_host::attributes
    wxStaticText* label_host_server_name;
    wxTextCtrl* text_host_server_nameData;
    wxStaticText* label_host_server_modType;
    wxChoice* choice_host_server_modData;
    wxStaticText* label_host_server_port;
    wxTextCtrl* text_host_server_portData;
    wxCheckBox* checkbox_host_server_privateGameData;
    wxCheckBox* checkbox_host_server_lanGameData;
    wxStaticText* label_host_server_maxPlayers;
    wxSlider* slider_host_server_maxPlayersData;
    wxStaticText* label_host_battle_maxUnitsData_copy;
    wxStaticText* label_host_server_maxUnits;
    wxTextCtrl* text_host_server_maxUnitsData;
    wxStaticText* label_host_server_startEnergy;
    wxTextCtrl* text_host_server_startEnergyData;
    wxStaticText* label_host_server_startMetal;
    wxTextCtrl* text_host_server_startMetalData;
    wxButton* button_host_server_ok;
    wxButton* button_host_server_cancel;
    wxButton* button_host_server_testHost;
    wxStaticBitmap* bitmap_host_map_preview;
    wxChoice* choice_host_map_mapData;
    wxStaticText* label_host_map_description_copy_2_copy_copy;
    wxTextCtrl* text_host_map_description;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_HOST_H
