# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sun Mar 12 15:08:06 2006

import wx

# begin wxGlade: dependencies
# end wxGlade

class gui_connect(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: gui_connect.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_connect_name = wx.StaticText(self, -1, "Name: ", style=wx.ALIGN_RIGHT)
        self.text_connect_nameData = wx.TextCtrl(self, 201, "", style=wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB)
        self.label_connect_password = wx.StaticText(self, -1, "Password: ")
        self.text_connect_passwordData = wx.TextCtrl(self, 202, "", style=wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB|wx.TE_PASSWORD)
        self.checkbox_connect_rememberLogin = wx.CheckBox(self, -1, "")
        self.label_connect_rememberLogin = wx.StaticText(self, -1, "Remember login")
        self.button_connect_login = wx.Button(self, 101, "Log In")
        self.button_connect_register = wx.Button(self, 102, "Register")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.text_connect_helpBox = wx.TextCtrl(self, -1, "Enter your username and password to log into the Master Server.\n\nIf you do not have a username and password, enter your desired username and password, and hit the \"Register\" button.  This will register your nickname and send you to the Spring Lobby. ", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_AUTO_URL)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: gui_connect.__set_properties
        self.SetTitle("Omni - Connect/Register")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("resource/spring-redlogo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.text_connect_nameData.SetMinSize((100, 25))
        self.text_connect_passwordData.SetMinSize((100, 25))
        self.checkbox_connect_rememberLogin.SetMinSize((22, 21))
        self.button_connect_login.SetToolTipString("Login with the username and password entered above")
        self.button_connect_login.SetDefault()
        self.button_connect_register.SetToolTipString("Register the username and password above and login")
        self.text_connect_helpBox.SetMinSize((275, 150))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: gui_connect.__do_layout
        grid_connect_main = wx.FlexGridSizer(4, 3, 0, 0)
        sizer_connect_helpBox = wx.BoxSizer(wx.VERTICAL)
        grid_connect_loginInfo = wx.GridSizer(6, 2, 3, 0)
        grid_connect_main.Add((10, 10), 0, 0, 0)
        grid_connect_main.Add((200, 10), 0, 0, 0)
        grid_connect_main.Add((10, 10), 0, 0, 0)
        grid_connect_main.Add((10, 100), 0, 0, 0)
        grid_connect_loginInfo.Add(self.label_connect_name, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_connect_loginInfo.Add(self.text_connect_nameData, 0, wx.FIXED_MINSIZE, 0)
        grid_connect_loginInfo.Add(self.label_connect_password, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_connect_loginInfo.Add(self.text_connect_passwordData, 0, wx.FIXED_MINSIZE, 0)
        grid_connect_loginInfo.Add(self.checkbox_connect_rememberLogin, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_connect_loginInfo.Add(self.label_connect_rememberLogin, 0, 0, 0)
        grid_connect_loginInfo.Add(self.button_connect_login, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_connect_loginInfo.Add(self.button_connect_register, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_connect_main.Add(grid_connect_loginInfo, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.SHAPED, 0)
        grid_connect_main.Add((10, 100), 0, 0, 0)
        grid_connect_main.Add((10, 100), 0, 0, 0)
        sizer_connect_helpBox.Add((20, 5), 0, 0, 0)
        sizer_connect_helpBox.Add(self.static_line_1, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_connect_helpBox.Add((20, 8), 0, 0, 0)
        sizer_connect_helpBox.Add(self.text_connect_helpBox, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_connect_main.Add(sizer_connect_helpBox, 2, wx.EXPAND, 0)
        grid_connect_main.Add((10, 100), 0, 0, 0)
        grid_connect_main.Add((10, 10), 0, 0, 0)
        grid_connect_main.Add((200, 10), 0, 0, 0)
        grid_connect_main.Add((10, 10), 0, 0, 0)
        self.SetAutoLayout(True)
        self.SetSizer(grid_connect_main)
        grid_connect_main.Fit(self)
        grid_connect_main.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class gui_connect


