# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sun Mar 12 15:08:06 2006

import wx

# begin wxGlade: dependencies
# end wxGlade

class gui_channel(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: gui_channel.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.list_channel_channels = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.text_channel_channel = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.button_channel_join = wx.Button(self, -1, "Join")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: gui_channel.__set_properties
        self.SetTitle("Omni - Join Channel")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("resource/spring-redlogo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((429, 265))
        self.list_channel_channels.SetToolTipString("Double-click a channel to join it")
        self.button_channel_join.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: gui_channel.__do_layout
        grid_channel_main = wx.FlexGridSizer(5, 3, 0, 0)
        sizer_10 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((50, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add(self.list_channel_channels, 0, wx.EXPAND, 0)
        grid_channel_main.Add((10, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((50, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.text_channel_channel, 0, wx.EXPAND, 0)
        sizer_10.Add(self.button_channel_join, 0, 0, 0)
        sizer_10.AddGrowableCol(0)
        grid_channel_main.Add(sizer_10, 1, wx.EXPAND, 0)
        grid_channel_main.Add((10, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((50, 10), 0, wx.ADJUST_MINSIZE, 0)
        grid_channel_main.Add((10, 10), 0, wx.ADJUST_MINSIZE, 0)
        self.SetAutoLayout(True)
        self.SetSizer(grid_channel_main)
        grid_channel_main.AddGrowableRow(1)
        grid_channel_main.AddGrowableCol(1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class gui_channel


