//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RtsSettingsWiz.rc
//
#define IDD_PPGENERAL                   100
#define IDD_PPTWEAKS                  116
#define IDR_MAINFRAME                   128
#define IDS_APP_TITLE                   130
#define IDI_MAIN                        131
#define IDS_STRING131                   131
#define IDD_PPPREGAMEGUI                150
#define IDD_PPTEMPLATE                  150
#define IDD_PPMAP                       200
#define IDD_PPENVIRONMENT               250
#define IDD_PPUNITS                     300
#define IDD_PPSOUND                     350
#define IDC_PPGENERAL_EDIT_PLAYERNAME   1000
#define IDC_PPGENERAL_COMBO_RES         1001
#define IDC_PPGENERAL_EDIT_XRESOLUTION  1002
#define IDC_PPGENERAL_EDIT_YRESOLUTION  1003
#define IDC_PPGENERAL_CHECK_FULLSCREEN  1004
#define IDC_PPGENERAL_CHECK_INVERTMOUSE 1005
#define IDC_PPTWEAKS_RADIO_USEREGISTRY 1065
#define IDC_PPTWEAKS_RADIO_USEFILE    1066
#define IDC_PPTWEAKS_CHECK_SHOWCLOCK  1067
#define IDC_PPTWEAKS_CHECK_SHOWPLAYERINFO 1068
#define IDC_PPTWEAKS_BUTTON_EXPORT    1070
#define IDC_PPMAP_CHECK_3DTREES         1200
#define IDC_PPMAP_SCRL_TREERADIUS       1201
#define IDC_PPMAP_SCRL_GRASSDETAIL      1202
#define IDC_PPMAP_SCRL_GROUNDDETAIL     1203
#define IDC_PPMAP_SCRL_GROUNDDECALS     1204
#define IDC_PPMAP_SCRL_MAXPARTICLES     1205
#define IDC_PPENVIRONMENT_CHECK_ADVSKY  1250
#define IDC_PPENVIRONMENT_CHECK_DYNAMICSKY 1251
#define IDC_PPENVIRONMENT_CHECK_REFLECTIVEWATER 1252
#define IDC_PPENVIRONMENT_CHECK_COLORELEV 1253
#define IDC_PPENVIRONMENT_CHECK_SHADOWS 1254
#define IDC_PPENVIRONMENT_RADIO_SHADOWMAPSIZE_1048 1255
#define IDC_PPENVIRONMENT_RADIO_SHADOWMAPSIZE_2048 1256
#define IDC_PPUNITS_SCRL_UNITLODDIST    1300
#define IDC_PPUNITS_RADIO_UNITTEXTUREQUALITY_1 1301
#define IDC_PPUNITS_RADIO_UNITTEXTUREQUALITY_2SAI 1302
#define IDC_PPUNITS_RADIO_UNITTEXTUREQUALITY_2HQ 1303
#define IDC_PPUNITS_RADIO_UNITTEXTUREQUALITY_4HQ 1304
#define IDC_PPSOUND_SCRL_MAXSOUNDS      1351

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
