/*
 * CBooleanOptionsPanel.java
 *
 * Created on 11 January 2008, 21:25
 */

package aflobby.UI.battle;

import aflobby.framework.CEvent;
import aflobby.IBattleModel;
import aflobby.LMain;
import aflobby.UI.DocumentSizeFilter;
import aflobby.framework.IModule;
import javax.swing.SwingUtilities;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author  tarendai-std
 */
public class CStringOptionsPanel extends javax.swing.JPanel implements IModule{
    
    int optionType;
    String defValue;
    int maxlength;
    String title;
    String description;
    String key;
    IBattleModel battlemodel;
    boolean map;
    boolean host;
    
    /** Creates new form CBooleanOptionsPanel
     * @param battlemodel 
     * @param key
     * @param defValue
     * @param maxlength 
     * @param title
     * @param description
     * @param map 
     */
    public CStringOptionsPanel(
            IBattleModel battlemodel, String key, String defValue, int maxlength, String title, String description, boolean map) {
        
        this.host = battlemodel.AmIHost();
        this.defValue = defValue;
        this.maxlength = maxlength;
        this.title = new String(title);
        this.key = new String(key);
        this.description = new String(description);
        this.battlemodel = battlemodel;
        this.map = map;
        
        battlemodel.PutOption(key, defValue);
        
        Runnable doWorkRunnable = new Runnable() {
            public void run() {
                initComponents();
            }
        };
        SwingUtilities.invokeLater(doWorkRunnable);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+5f));
        jLabel1.setText(title);

        jLabel2.setText(description);

        jButton2.setText("Reset");
        jButton2.setEnabled(host);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextField.setNextFocusableComponent(jButton2);
        AbstractDocument doc = (AbstractDocument)TextField.getDocument();
        doc.setDocumentFilter(new DocumentSizeFilter(3));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UI/map.png"))); // NOI18N
        jLabel3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UI/optionflag.png"))); // NOI18N
        jLabel3.setEnabled(map);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Runnable doWorkRunnable = new Runnable() {
            public void run() {
                TextField.setText(defValue);
            }
        };
        SwingUtilities.invokeLater(doWorkRunnable);
        battlemodel.PutOption(key, TextField.getText());
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void Init(LMain L) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void Update() {
        
    }

    public void NewEvent(final CEvent e) {
        if(e.IsEvent("SETSCRIPTTAGS")){
            //
            String[] pairs = e.parameters.split("\t");
            
            for(int i = 0; i< pairs.length; i++){
                
                String[] pair = pairs[i].split("=");
                
                String k = pair[0];
                k = k.replaceAll("\\\\", "/");
                final String value = pair[1];
                
                if(k.equalsIgnoreCase(key)){
                    Runnable doWorkRunnable = new Runnable() {
                        public void run() {
                            TextField.setText(value);
                        }
                    };
                    SwingUtilities.invokeLater(doWorkRunnable);
                    
                }
                
            }
        }
    }

    public void NewGUIEvent(CEvent e) {

    }

    public void OnRemove() {
        battlemodel = null;
    }
    
}
