// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include "gui_agreement.h"


gui_agreement::gui_agreement(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: gui_agreement::gui_agreement
    text_agreement_data = new wxTextCtrl(this, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxTE_RICH);
    radio_agreement_agree = new wxRadioButton(this, -1, wxT("I have read the above agreement and agree to its terms."), wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    radio_agreement_disagree = new wxRadioButton(this, -1, wxT("I do not agree to these terms."));
    button_agreement_continue = new wxButton(this, -1, wxT("Continue"));

    set_properties();
    do_layout();
    // end wxGlade
}


void gui_agreement::set_properties()
{
    // begin wxGlade: gui_agreement::set_properties
    SetTitle(wxT("Spring Agreement"));
    wxIcon _icon;
    _icon.CopyFromBitmap(wxBitmap(wxT("resource/spring-redlogo.png"), wxBITMAP_TYPE_ANY));
    SetIcon(_icon);
    SetSize(wxSize(629, 389));
    text_agreement_data->SetMinSize(wxSize(486, 265));
    radio_agreement_disagree->SetValue(1);
    button_agreement_continue->SetDefault();
    // end wxGlade
}


void gui_agreement::do_layout()
{
    // begin wxGlade: gui_agreement::do_layout
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(5, 3, 0, 0);
    wxFlexGridSizer* grid_sizer_4 = new wxFlexGridSizer(2, 1, 0, 0);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxVERTICAL);
    grid_sizer_3->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(20, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(text_agreement_data, 0, wxEXPAND, 0);
    grid_sizer_3->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(5, 5, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(20, 5, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    sizer_9->Add(radio_agreement_agree, 0, 0, 0);
    sizer_9->Add(radio_agreement_disagree, 0, 0, 0);
    sizer_9->Add(50, 20, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_4->Add(sizer_9, 1, wxEXPAND, 0);
    grid_sizer_4->Add(button_agreement_continue, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    grid_sizer_4->AddGrowableRow(0);
    grid_sizer_4->AddGrowableRow(1);
    grid_sizer_4->AddGrowableCol(0);
    grid_sizer_3->Add(grid_sizer_4, 1, wxEXPAND, 0);
    grid_sizer_3->Add(10, 20, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(20, 10, 0, wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(10, 10, 0, wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(grid_sizer_3);
    grid_sizer_3->AddGrowableRow(1);
    grid_sizer_3->AddGrowableCol(1);
    Layout();
    Centre();
    // end wxGlade
}

