// -*- C++ -*- generated by wxGlade 0.3.5.1 on Tue May  3 19:18:59 2005

#include <wx/wx.h>
#include <wx/image.h>
#include "lobby_main.h"



class wxGUI: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(wxGUI)

bool wxGUI::OnInit()
{
    wxInitAllImageHandlers();
    lobby_main* lobby = new lobby_main(0, -1, "");
    SetTopWindow(lobby);
    lobby->Show();
    return true;
}
