// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_BATTLEROOM_H
#define GUI_BATTLEROOM_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
// end wxGlade


class gui_battleroom: public wxFrame {
public:
    // begin wxGlade: gui_battleroom::ids
    // end wxGlade

    gui_battleroom(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: gui_battleroom::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_battleroom::attributes
    wxStaticText* label_battleroom_players_status;
    wxStaticBitmap* bitmap_battleroom_players_icon_player1;
    wxComboBox* combo_battleroom_players_status_player1;
    wxStaticBitmap* bitmap_battleroom_players_icon_player2;
    wxComboBox* combo_battleroom_players_status_player2;
    wxStaticBitmap* bitmap_battleroom_players_icon_player3;
    wxComboBox* combo_battleroom_players_status_player3;
    wxStaticBitmap* bitmap_battleroom_players_icon_player4;
    wxComboBox* combo_battleroom_players_status_player4;
    wxStaticBitmap* bitmap_battleroom_players_icon_player5;
    wxComboBox* combo_battleroom_players_status_player5;
    wxStaticBitmap* bitmap_battleroom_players_icon_player6;
    wxComboBox* combo_battleroom_players_status_player6;
    wxStaticBitmap* bitmap_battleroom_players_icon_player7;
    wxComboBox* combo_battleroom_players_status_player7;
    wxStaticBitmap* bitmap_battleroom_players_icon_player8;
    wxComboBox* combo_battleroom_players_status_player8;
    wxStaticBitmap* bitmap_battleroom_players_icon_player9;
    wxComboBox* combo_battleroom_players_status_player9;
    wxStaticBitmap* bitmap_battleroom_players_icon_player10;
    wxComboBox* combo_battleroom_players_status_player10;
    wxStaticBitmap* bitmap_battleroom_players_icon_player11;
    wxComboBox* combo_battleroom_players_status_player11;
    wxStaticBitmap* bitmap_battleroom_players_icon_player12;
    wxComboBox* combo_battleroom_players_status_player12;
    wxStaticBitmap* bitmap_battleroom_players_icon_player13;
    wxComboBox* combo_battleroom_players_status_player13;
    wxStaticBitmap* bitmap_battleroom_players_icon_player14;
    wxComboBox* combo_battleroom_players_status_player14;
    wxStaticBitmap* bitmap_battleroom_players_icon_player15;
    wxComboBox* combo_battleroom_players_status_player15;
    wxStaticBitmap* bitmap_battleroom_players_icon_player16;
    wxComboBox* combo_battleroom_players_status_player16;
    wxStaticText* label_battleroom_players_faction;
    wxComboBox* combo_battleroom_players_faction_player1;
    wxComboBox* combo_battleroom_players_faction_player2;
    wxComboBox* combo_battleroom_players_faction_player3;
    wxComboBox* combo_battleroom_players_faction_player4;
    wxComboBox* combo_battleroom_players_faction_player5;
    wxComboBox* combo_battleroom_players_faction_player6;
    wxComboBox* combo_battleroom_players_faction_player7;
    wxComboBox* combo_battleroom_players_faction_player8;
    wxComboBox* combo_battleroom_players_faction_player9;
    wxComboBox* combo_battleroom_players_faction_player10;
    wxComboBox* combo_battleroom_players_faction_player11;
    wxComboBox* combo_battleroom_players_faction_player12;
    wxComboBox* combo_battleroom_players_faction_player13;
    wxComboBox* combo_battleroom_players_faction_player14;
    wxComboBox* combo_battleroom_players_faction_player15;
    wxComboBox* combo_battleroom_players_faction_player16;
    wxStaticText* label_battleroom_players_sharedArmy;
    wxComboBox* combo_battleroom_players_sharedArmy_player1;
    wxComboBox* combo_battleroom_players_sharedArmy_player2;
    wxComboBox* combo_battleroom_players_sharedArmy_player3;
    wxComboBox* combo_battleroom_players_sharedArmy_player4;
    wxComboBox* combo_battleroom_players_sharedArmy_player5;
    wxComboBox* combo_battleroom_players_sharedArmy_player6;
    wxComboBox* combo_battleroom_players_sharedArmy_player7;
    wxComboBox* combo_battleroom_players_sharedArmy_player8;
    wxComboBox* combo_battleroom_players_sharedArmy_player9;
    wxComboBox* combo_battleroom_players_sharedArmy_player10;
    wxComboBox* combo_battleroom_players_sharedArmy_player11;
    wxComboBox* combo_battleroom_players_sharedArmy_player12;
    wxComboBox* combo_battleroom_players_sharedArmy_player13;
    wxComboBox* combo_battleroom_players_sharedArmy_player14;
    wxComboBox* combo_battleroom_players_sharedArmy_player15;
    wxComboBox* combo_battleroom_players_sharedArmy_player16;
    wxStaticText* label_battleroom_players_team;
    wxComboBox* combo_battleroom_players_team_player1;
    wxComboBox* combo_battleroom_players_team_player2;
    wxComboBox* combo_battleroom_players_team_player3;
    wxComboBox* combo_battleroom_players_team_player4;
    wxComboBox* combo_battleroom_players_team_player5;
    wxComboBox* combo_battleroom_players_team_player6;
    wxComboBox* combo_battleroom_players_team_player7;
    wxComboBox* combo_battleroom_players_team_player8;
    wxComboBox* combo_battleroom_players_team_player9;
    wxComboBox* combo_battleroom_players_team_player10;
    wxComboBox* combo_battleroom_players_team_player11;
    wxComboBox* combo_battleroom_players_team_player12;
    wxComboBox* combo_battleroom_players_team_player13;
    wxComboBox* combo_battleroom_players_team_player14;
    wxComboBox* combo_battleroom_players_team_player15;
    wxComboBox* combo_battleroom_players_team_player16;
    wxStaticText* label_battleroom_players_handicap;
    wxSpinCtrl* spin_battleroom_players_handicap_player1;
    wxSpinCtrl* spin_battleroom_players_handicap_player2;
    wxSpinCtrl* spin_battleroom_players_handicap_player3;
    wxSpinCtrl* spin_battleroom_players_handicap_player4;
    wxSpinCtrl* spin_battleroom_players_handicap_player5;
    wxSpinCtrl* spin_battleroom_players_handicap_player6;
    wxSpinCtrl* spin_battleroom_players_handicap_player7;
    wxSpinCtrl* spin_battleroom_players_handicap_player8;
    wxSpinCtrl* spin_battleroom_players_handicap_player9;
    wxSpinCtrl* spin_battleroom_players_handicap_player10;
    wxSpinCtrl* spin_battleroom_players_handicap_player11;
    wxSpinCtrl* spin_battleroom_players_handicap_player12;
    wxSpinCtrl* spin_battleroom_players_handicap_player13;
    wxSpinCtrl* spin_battleroom_players_handicap_player14;
    wxSpinCtrl* spin_battleroom_players_handicap_player15;
    wxSpinCtrl* spin_battleroom_players_handicap_player16;
    wxStaticText* label_battleroom_players_ready;
    wxCheckBox* checkbox_battleroom_ready_player1;
    wxCheckBox* checkbox_battleroom_ready_player2;
    wxCheckBox* checkbox_battleroom_ready_player3;
    wxCheckBox* checkbox_battleroom_ready_player4;
    wxCheckBox* checkbox_battleroom_ready_player5;
    wxCheckBox* checkbox_battleroom_ready_player6;
    wxCheckBox* checkbox_battleroom_ready_player7;
    wxCheckBox* checkbox_battleroom_ready_player8;
    wxCheckBox* checkbox_battleroom_ready_player9;
    wxCheckBox* checkbox_battleroom_ready_player10;
    wxCheckBox* checkbox_battleroom_ready_player11;
    wxCheckBox* checkbox_battleroom_ready_player12;
    wxCheckBox* checkbox_battleroom_ready_player13;
    wxCheckBox* checkbox_battleroom_ready_player14;
    wxCheckBox* checkbox_battleroom_ready_player15;
    wxCheckBox* checkbox_battleroom_ready_player16;
    wxStaticText* label_battleroom_players_sync;
    wxStaticBitmap* bitmap_battleroom_players_sync_player1;
    wxStaticBitmap* bitmap_battleroom_players_sync_player2;
    wxStaticBitmap* bitmap_battleroom_players_sync_player3;
    wxStaticBitmap* bitmap_battleroom_players_sync_player4;
    wxStaticBitmap* bitmap_battleroom_players_sync_player5;
    wxStaticBitmap* bitmap_battleroom_players_sync_player6;
    wxStaticBitmap* bitmap_battleroom_players_sync_player7;
    wxStaticBitmap* bitmap_battleroom_players_sync_player8;
    wxStaticBitmap* bitmap_battleroom_players_sync_player9;
    wxStaticBitmap* bitmap_battleroom_players_sync_player10;
    wxStaticBitmap* bitmap_battleroom_players_sync_player11;
    wxStaticBitmap* bitmap_battleroom_players_sync_player12;
    wxStaticBitmap* bitmap_battleroom_players_sync_player13;
    wxStaticBitmap* bitmap_battleroom_players_sync_player14;
    wxStaticBitmap* bitmap_battleroom_players_sync_player15;
    wxStaticBitmap* bitmap_battleroom_players_sync_player16;
    wxStaticText* label_battleroom_players_ping;
    wxStaticBitmap* bitmap_battleroom_players_ping_player1;
    wxStaticBitmap* bitmap_battleroom_players_ping_player2;
    wxStaticBitmap* bitmap_battleroom_players_ping_player3;
    wxStaticBitmap* bitmap_battleroom_players_ping_player4;
    wxStaticBitmap* bitmap_battleroom_players_ping_player5;
    wxStaticBitmap* bitmap_battleroom_players_ping_player6;
    wxStaticBitmap* bitmap_battleroom_players_ping_player7;
    wxStaticBitmap* bitmap_battleroom_players_ping_player8;
    wxStaticBitmap* bitmap_battleroom_players_ping_player9;
    wxStaticBitmap* bitmap_battleroom_players_ping_player10;
    wxStaticBitmap* bitmap_battleroom_players_ping_player11;
    wxStaticBitmap* bitmap_battleroom_players_ping_player12;
    wxStaticBitmap* bitmap_battleroom_players_ping_player13;
    wxStaticBitmap* bitmap_battleroom_players_ping_player14;
    wxStaticBitmap* bitmap_battleroom_players_ping_player15;
    wxStaticBitmap* bitmap_battleroom_players_ping_player16;
    wxTextCtrl* text_battleroom_players_chatarea;
    wxTextCtrl* text_battleroom_players_msgbox;
    wxButton* button_battleroom_players_sendmsg;
    wxStaticText* label_battleroom_server_battleName;
    wxTextCtrl* text_battleroom_server_nameData;
    wxStaticText* label_battleroom_server_mapName;
    wxTextCtrl* text_battleroom_server_map;
    wxStaticText* label_battleroom_server_modName;
    wxTextCtrl* text_battleroom_server_mod;
    wxStaticText* label_battleroom_server_maxUnits;
    wxTextCtrl* text_battleroom_server_maxUnitsData;
    wxStaticText* label_battleroom_server_startEnergy;
    wxTextCtrl* text_battleroom_server_startEnergyData;
    wxStaticText* label_battleroom_server_startMetal;
    wxTextCtrl* text_battleroom_server_startMetalData;
    wxCheckBox* checkbox_battleroom_server_handicap;
    wxCheckBox* checkbox_battleroom_server_hostModifiesHandicaps;
    wxStaticText* label_battleroom_map_startPos;
    wxChoice* choice_battleroom_map_startPosData;
    wxStaticText* label_battleroom_map_winConditions;
    wxChoice* choice_battleroom_map_winConditionData;
    wxCheckBox* checkbox_battleroom_server_rememberBuildingsLOS;
    wxCheckBox* checkbox_battleroom_server_limitdgunData;
    wxButton* button_battleroom_server_startGame;
    wxPanel* panel_battleroom_server;
    wxStaticBitmap* bitmap_battleroom_map_preview;
    wxChoice* choice_battleroom_map_mapData;
    wxStaticText* label_battleroom_map_description;
    wxTextCtrl* text_battleroom_map_description;
    wxStaticText* label_battleroom_map_tidal;
    wxSpinCtrl* spin_battleroom_map_tidalData;
    wxStaticText* label_battleroom_map_gravity;
    wxSpinCtrl* spin_battleroom_map_gravityData;
    wxStaticText* label_battleroom_map_maxMetal;
    wxSpinCtrl* spin_battleroom_map_maxMetalData;
    wxStaticText* label_battleroom_map_extractorRadius;
    wxSpinCtrl* spin_battleroom_map_extractorRadiusData;
    wxStaticText* label_battleroom_map_minWind;
    wxSpinCtrl* spin_battleroom_map_minWindData;
    wxStaticText* label_battleroom_map_maxWind;
    wxSpinCtrl* spin_battleroom_map_maxWindData;
    wxStaticText* label_battleroom_map_hardness;
    wxSpinCtrl* spin_battleroom_map_hardnessData;
    wxButton* button_battleroom_map_revertToDefaults;
    wxButton* button_battleroom_map_disabledUnits;
    wxPanel* panel_battleroom_map;
    wxStaticBitmap* bitmap_battleroom_mod_preview;
    wxChoice* choice_battleroom_mod_modData;
    wxStaticText* label_battleroom_mod_fileList;
    wxTreeCtrl* tree_battleroom_mod_fileList;
    wxStaticText* label_battleroom_mod_description;
    wxTextCtrl* text_battleroom_mod_description;
    wxStaticText* label_battleroom_mod_settings;
    wxListCtrl* list_battleroom_mod_settings;
    wxTextCtrl* text_battleroom_mod_settingInputData;
    wxButton* button_battleroom_mod_updateSetting;
    wxButton* button_battleroom_mod_defaultSetting;
    wxButton* button_battleroom_mod_revertToDefaults;
    wxPanel* panel_battleroom_mod;
    wxNotebook* notebook_battleroom_settings;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_BATTLEROOM_H
