// -*- C++ -*- generated by wxGlade 0.4 on Sat Dec 31 11:17:21 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GUI_CLSETTINGS_H
#define GUI_CLSETTINGS_H

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


class gui_clSettings: public wxFrame {
public:
    // begin wxGlade: gui_clSettings::ids
    // end wxGlade

    gui_clSettings(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: gui_clSettings::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: gui_clSettings::attributes
    wxStaticText* label_clsettings_colorPrefs;
    wxStaticText* label_clSettings_interface_firstColor;
    wxButton* button_clSettings_interface_firstColor;
    wxStaticText* label_clSettings_interface_secondColor;
    wxButton* button_clSettings_interface_secondColor;
    wxStaticText* label_clSettings_interface_thirdColor;
    wxButton* button_clSettings_interface_thirdColor;
    wxStaticText* label_clSettings_textColors;
    wxStaticText* label_clSettings_interface_channelText;
    wxButton* button_clSettings_interface_channelText;
    wxStaticText* label_clSettings_interface_userText;
    wxButton* button_clSettings_interface_userText;
    wxStaticText* label_clSettings_interface_privateText;
    wxButton* button_clSettings_interface_privateText;
    wxStaticText* label_clSettings_interface_serverText;
    wxButton* button_clSettings_interface_serverText;
    wxStaticText* label_clSettings_interface_debugText;
    wxButton* button_clSettings_interface_debugText;
    wxPanel* notebook_clSettings_interface;
    wxCheckBox* checkbox_clSettings_options_customIcon;
    wxTextCtrl* text_clSettings_options_customIconPath;
    wxButton* button_clSettings_options_findCustomIconPath;
    wxTextCtrl* text_clSettings_options_customIconRules;
    wxCheckBox* checkbox_clSettings_options_showCustomIcons;
    wxStaticText* label_clSettings_options_showCustomIcons;
    wxCheckBox* checkbox_clSettings_options_createLanTab;
    wxStaticText* label_clSettings_options_createLanTab;
    wxStaticText* label_clSettings_options_defaultFaction;
    wxChoice* choice_clSettings_options_defaultFactionData;
    wxPanel* notebook_1_pane_2_copy;
    wxPanel* notebook_clSettings_options;
    wxCheckBox* checkbox_clSettings_advanced_rememberAll;
    wxStaticText* label_clSettings_advanced_rememberAll;
    wxCheckBox* checkbox_clSettings_advanced_blockPrivate;
    wxStaticText* label_clSettings_advanced_blockPrivate;
    wxCheckBox* checkbox_clSettings_advanced_showDebug;
    wxStaticText* label_clSettings_advanced_showDebug;
    wxCheckBox* checkbox_clSettings_advanced_donateBandwidth;
    wxStaticText* label_clSettings_advanced_donateBandwidth;
    wxStaticText* label_clSettings_advanced_maxUpload;
    wxComboBox* combo_clSettings_advanced_maxUpload;
    wxStaticText* label_kilobytes_copy;
    wxStaticText* label_clSettings_advanced_bitPort;
    wxTextCtrl* text_clSettings_advanced_bitPortData;
    wxCheckBox* checkbox_clSettings_advanced_ipConfig;
    wxStaticText* label_clSettings_advanced_ipConfig;
    wxTextCtrl* text_clSettings_advanced_ipUsedData;
    wxPanel* notebook_clSettings_advanced;
    wxNotebook* notebook_clSettings_main;
    wxButton* button_clSettings_main_save;
    wxButton* button_clSettings_main_revertToDefaults;
    wxButton* button_clSettings_main_done;
    // end wxGlade
}; // wxGlade: end class


#endif // GUI_CLSETTINGS_H
